### ISSUE TITLE
BasePLModule got an unexpected keyword argument

### ISSUE THREAD

**Issue by LeonardoEmili** [edobobo/p-lightning-template#7]
Hi, and first of all, thanks for providing this great template! 

## Description
At inference time, the test script crashes when passing extra keyword arguments to the method `load_from_checkpoint` to load a model checkpoint. In fact, kwargs are later expanded during the upstream calls and passed to BasePLModule that does not have a keyword argument for them. It happens in the `BasePLModule` class constructor through the method [_load_model_state](https://github.com/PyTorchLightning/pytorch-lightning/blob/47e7a2860fc6c6f8d4a9117e213d9f5c0246d4f4/pytorch_lightning/core/saving.py#L198).

## Workaround
I managed to solve the issue by calling the `LightningModule`'s without any args/kwargs. Furthermore, as stated by the [PL documentation](https://pytorch-lightning.readthedocs.io/en/latest/common/lightning_module.html#minimal-example) it seems not required to pass any args/kwargs when calling the super-constructor.

If you want, I can open a PR or you can do it by yourself since it is a one-line fix.

**Comment by edobobo** [comment]
If you can open a PR please. Thanks in advance for the contribution!

**Comment by LeonardoEmili** [comment]
I opened a PR that fixes the issue @edobobo, feel free to merge it if it looks good to you.
